version: '3'

networks:
  default:
    external:
      name: network

services:

  pingbot:
    container_name: pingbot
    image: alsoeast/pingbot:1.1
    restart: always
    volumes:
      - ./config.yaml:/usr/src/app/config.yaml
